
CREATE TABLE MUSICA (
                CODIGO_MUSICA INTEGER NOT NULL,
                NOME VARCHAR(30) NOT NULL,
                DATA_LANCAMENTO DATE NOT NULL,
                CONSTRAINT MUSICA_pk PRIMARY KEY (CODIGO_MUSICA)
);



CREATE TABLE CANTOR_BANDA (
                CODIGO_CANTOR_BANDA INTEGER NOT NULL,
                TIPO SMALLINT NOT NULL,
                NOME VARCHAR(30) NOT NULL,
                CONSTRAINT CANTOR_BANDA_pk PRIMARY KEY (CODIGO_CANTOR_BANDA)
);


CREATE TABLE GRAVACAO_MUSICA (
                CODIGO_CANTOR_BANDA INTEGER NOT NULL,
                CODIGO_MUSICA INTEGER NOT NULL,
                DATA_GRAVACAO DATE NOT NULL,
                DURACAO_MUSICA TIME NOT NULL,
                CONSTRAINT GRAVACAO_MUSICA_pk PRIMARY KEY (CODIGO_CANTOR_BANDA, CODIGO_MUSICA)
);


ALTER TABLE GRAVACAO_MUSICA ADD CONSTRAINT MUSICA_GRAVACAO_MUSICA_fk
FOREIGN KEY (CODIGO_MUSICA)
REFERENCES MUSICA (CODIGO_MUSICA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE GRAVACAO_MUSICA ADD CONSTRAINT CANTOR_BANDA_GRAVACAO_MUSICA_fk
FOREIGN KEY (CODIGO_CANTOR_BANDA)
REFERENCES CANTOR_BANDA (CODIGO_CANTOR_BANDA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
